'use client';
import {useEffect,useState} from 'react';
import {api,login} from '../lib/api';

type Section='dashboard'|'content'|'calendar'|'inbox'|'comments'|'crm'|'analytics'|'instagram'|'ai'|'settings';
const nav:[Section,string][]=[['dashboard','داشبورد'],['content','محتوا'],['calendar','تقویم'],['inbox','صندوق پیام'],['comments','کامنت‌ها'],['crm','CRM'],['analytics','آنالیز'],['instagram','اینستاگرام'],['ai','دستیار AI'],['settings','تنظیمات']];

export default function Home(){
 const [token,setToken]=useState<string|null>(null); const [section,setSection]=useState<Section>('dashboard'); const [workspace,setWorkspace]=useState<any>(null); const [loading,setLoading]=useState(true);
 useEffect(()=>{setToken(localStorage.getItem('access_token'));setLoading(false)},[]);
 if(loading)return <div className="login"><div>در حال بارگذاری…</div></div>;
 if(!token)return <Login onDone={()=>setToken(localStorage.getItem('access_token'))}/>;
 return <div className="shell"><aside className="sidebar"><div className="brand">✦ InstaMind AI</div><div className="nav">{nav.map(([id,label])=><button key={id} className={section===id?'active':''} onClick={()=>setSection(id)}>{label}</button>)}</div><button className="btn secondary" style={{width:'100%',marginTop:20}} onClick={()=>{localStorage.clear();location.reload()}}>خروج</button></aside><main className="main"><div className="top"><div><div className="title">{nav.find(x=>x[0]===section)?.[1]}</div><div className="sub">مدیریت هوشمند و چندمستاجری اینستاگرام</div></div></div><WorkspaceBoot onReady={setWorkspace}/>{section==='dashboard'&&<Dashboard/>}{section==='content'&&<Content/>}{section==='calendar'&&<Calendar/>}{section==='inbox'&&<Inbox/>}{section==='comments'&&<Comments/>}{section==='crm'&&<CRM/>}{section==='analytics'&&<Analytics/>}{section==='instagram'&&<Instagram/>}{section==='ai'&&<AI/>}{section==='settings'&&<Settings/>}</main></div>
}
function WorkspaceBoot({onReady}:{onReady:(w:any)=>void}){useEffect(()=>{api<any[]>('/workspaces').then(ws=>{if(ws[0]){localStorage.setItem('workspace_id',ws[0].id);onReady(ws[0])}}).catch(()=>{})},[onReady]);return null}
function Login({onDone}:{onDone:()=>void}){const[e,setE]=useState('');const[p,setP]=useState('');const[err,setErr]=useState('');return <div className="login"><div className="card loginbox"><div className="brand">✦ InstaMind AI</div><h1>ورود به Workspace</h1><div className="sub">حساب سازمانی خود را وارد کنید.</div><label>ایمیل<input className="field" value={e} onChange={x=>setE(x.target.value)} /></label><label>رمز عبور<input type="password" className="field" value={p} onChange={x=>setP(x.target.value)}/></label>{err&&<p className="danger">{err}</p>}<button className="btn" style={{width:'100%',marginTop:12}} onClick={()=>login(e,p).then(onDone).catch(x=>setErr(x.message))}>ورود</button></div></div>}
function Dashboard(){const[data,setData]=useState<any>(null);useEffect(()=>{Promise.all([api<any[]>('/social-accounts'),api<any[]>('/content'),api<any[]>('/publishing/jobs'),api<any[]>('/engagement/conversations')]).then(([a,c,j,i])=>setData({a,c,j,i})).catch(()=>setData({a:[],c:[],j:[],i:[]}))},[]);if(!data)return <div className="card">در حال دریافت داده‌ها…</div>;return <><div className="grid"><Metric t="اکانت متصل" v={data.a.length}/><Metric t="محتوا" v={data.c.length}/><Metric t="Jobهای انتشار" v={data.j.length}/><Metric t="گفت‌وگوها" v={data.i.length}/></div><div className="grid2"><div className="card"><h3>محتوای اخیر</h3><div className="list">{data.c.slice(0,6).map((x:any)=><div className="item" key={x.id}><div className="row between"><b>{x.title||'بدون عنوان'}</b><span className="pill">{x.status}</span></div><div className="sub">{x.scheduled_at?new Date(x.scheduled_at).toLocaleString('fa-IR'):'بدون زمان‌بندی'}</div></div>)}</div></div><div className="card"><h3>وضعیت Instagram</h3>{data.a.length?<div className="list">{data.a.map((x:any)=><div className="item" key={x.id}><b>@{x.username}</b><div className="sub">{x.account_type||'—'} · <span className="ok">{x.status}</span></div></div>)}</div>:<div className="empty">هنوز اکانتی متصل نشده است.</div>}</div></div></>}
function Metric({t,v}:{t:string,v:any}){return <div className="card"><div className="label">{t}</div><div className="metric">{v}</div></div>}
function Content(){const[rows,setRows]=useState<any[]>([]);const[title,setTitle]=useState('');const[caption,setCaption]=useState('');const load=()=>api<any[]>('/content').then(setRows);useEffect(()=>{load().catch(()=>{})},[]);return <div className="grid2"><div className="card"><h3>ایجاد پیش‌نویس</h3><input className="field" placeholder="عنوان" value={title} onChange={e=>setTitle(e.target.value)}/><textarea className="field textarea" placeholder="کپشن" value={caption} onChange={e=>setCaption(e.target.value)}/><button className="btn" onClick={()=>api('/content',{method:'POST',body:JSON.stringify({title,caption,content_type:'IMAGE'})}).then(()=>{setTitle('');setCaption('');load()}).catch(alert)}>ذخیره پیش‌نویس</button></div><div className="card"><h3>محتوا</h3><div className="list">{rows.map(x=><div className="item" key={x.id}><b>{x.title||'بدون عنوان'}</b><div className="sub">{x.status}</div><p>{x.caption}</p></div>)}</div></div></div>}
function Calendar(){const[start]=useState(()=>new Date().toISOString());const[end]=useState(()=>new Date(Date.now()+30*864e5).toISOString());const[rows,setRows]=useState<any[]>([]);useEffect(()=>{api<any[]>(`/content/calendar?start=${encodeURIComponent(start)}&end=${encodeURIComponent(end)}`).then(setRows).catch(()=>{})},[start,end]);return <div className="card"><h3>تقویم انتشار</h3><div className="list">{rows.map(x=><div className="item" key={x.id}><b>{x.title}</b><div className="sub">{new Date(x.starts_at).toLocaleString('fa-IR')} · {x.event_type}</div></div>)}</div>{!rows.length&&<div className="empty">رویدادی برای این بازه وجود ندارد.</div>}</div>}
function Inbox(){const[rows,setRows]=useState<any[]>([]);const[selected,setSelected]=useState<any>(null);const[msgs,setMsgs]=useState<any[]>([]);const[text,setText]=useState('');const load=()=>api<any[]>('/engagement/conversations').then(setRows);useEffect(()=>{load().catch(()=>{})},[]);useEffect(()=>{if(selected)api<any[]>(`/engagement/conversations/${selected.id}/messages`).then(setMsgs).catch(()=>{})},[selected]);return <div className="grid2"><div className="card"><h3>گفت‌وگوها</h3><div className="list">{rows.map(x=><button className="item" style={{textAlign:'right'}} key={x.id} onClick={()=>setSelected(x)}><b>{x.participant_name||x.participant_username||'مخاطب'}</b><div className="sub">{x.status} · {x.is_read?'خوانده':'جدید'}</div></button>)}</div></div><div className="card"><h3>{selected?.participant_name||'پیام‌ها'}</h3>{selected?<><div className="list">{msgs.map(m=><div className="item" key={m.id}><span className="pill">{m.direction}</span><p>{m.text}</p></div>)}</div><textarea className="field" value={text} onChange={e=>setText(e.target.value)} placeholder="پاسخ انسانی…"/><button className="btn" onClick={()=>api(`/engagement/conversations/${selected.id}/messages`,{method:'POST',body:JSON.stringify({text})}).then(()=>{setText('');api<any[]>(`/engagement/conversations/${selected.id}/messages`).then(setMsgs)}).catch(alert)}>ارسال</button></>:<div className="empty">یک گفت‌وگو انتخاب کنید.</div>}</div></div>}
function Comments(){const[rows,setRows]=useState<any[]>([]);useEffect(()=>{api<any[]>('/engagement/comments').then(setRows).catch(()=>{})},[]);return <div className="card"><h3>کامنت‌ها</h3><div className="list">{rows.map(x=><div className="item" key={x.id}><div className="row between"><b>@{x.from_username||'user'}</b><span className="pill">{x.status}</span></div><p>{x.text}</p></div>)}</div>{!rows.length&&<div className="empty">کامنتی از Meta sync نشده است.</div>}</div>}
function CRM(){const[rows,setRows]=useState<any[]>([]);useEffect(()=>{api<any[]>('/engagement/customers').then(setRows).catch(()=>{})},[]);return <div className="card"><h3>مشتریان</h3><div className="list">{rows.map(x=><div className="item" key={x.id}><div className="row between"><b>{x.display_name||x.username||'مشتری'}</b><span className="pill">{x.stage}</span></div><div className="sub">Lead score: {x.lead_score} · {x.email||'بدون ایمیل'}</div></div>)}</div>{!rows.length&&<div className="empty">CRM هنوز داده‌ای ندارد.</div>}</div>}
function Analytics(){const[rows,setRows]=useState<any[]>([]);useEffect(()=>{api<any[]>('/engagement/analytics').then(setRows).catch(()=>{})},[]);return <div className="card"><h3>Analytics</h3><div className="list">{rows.map(x=><div className="item" key={x.id}><b>{x.metric}</b><div className="sub">{x.is_available?x.value:'No data available'} · {new Date(x.until).toLocaleDateString('fa-IR')}</div></div>)}</div>{!rows.length&&<div className="empty">هیچ Snapshotای از Insights ثبت نشده است.</div>}</div>}
function Instagram(){const[rows,setRows]=useState<any[]>([]);useEffect(()=>{api<any[]>('/social-accounts').then(setRows).catch(()=>{})},[]);const connect=()=>api<any>('/social-accounts/connect',{method:'POST',body:JSON.stringify({api_path:'INSTAGRAM_LOGIN'})}).then(x=>location.href=x.authorize_url).catch(alert);return <div className="card"><div className="row between"><h3>Instagram Accounts</h3><button className="btn" onClick={connect}>اتصال Instagram</button></div><div className="list">{rows.map(x=><div className="item" key={x.id}><b>@{x.username}</b><div className="sub">{x.account_type} · {x.status}</div><pre style={{whiteSpace:'pre-wrap'}}>{JSON.stringify(x.capabilities,null,2)}</pre></div>)}</div></div>}
function AI(){const[topic,setTopic]=useState('');const[result,setResult]=useState<any>(null);const[loading,setLoading]=useState(false);return <div className="card"><h3>AI Caption Studio</h3><input className="field" value={topic} onChange={e=>setTopic(e.target.value)} placeholder="موضوع محتوا"/><div className="actions"><button className="btn" disabled={loading} onClick={()=>{setLoading(true);api<any>('/ai/generate-caption',{method:'POST',body:JSON.stringify({topic,language:'fa-IR',tone:['professional'],max_hashtags:8,include_cta:true})}).then(setResult).catch(alert).finally(()=>setLoading(false))}}>{loading?'در حال تولید…':'تولید کپشن'}</button></div>{result&&<div className="item" style={{marginTop:16}}><p>{result.caption}</p><p>{result.hashtags?.map((x:string)=>`#${x} `)}</p>{result.warnings?.length>0&&<div className="danger">{result.warnings.join(' · ')}</div>}</div>}</div>}
function Settings(){return <div className="card"><h3>تنظیمات</h3><p className="sub">مدیریت Workspace، اعضا، نقش‌ها، امنیت و اتصال‌ها از APIهای موجود انجام می‌شود.</p><div className="actions"><button className="btn secondary" onClick={()=>location.href='/docs'}>API Docs</button></div></div>}
